import type {
  RuntimeControlSnapshot,
  RuntimeControlSurface,
} from '../runtime/runtime-control'

/**
 * Stable outcomes recorded after one runtime-control evaluation.
 */
export type RuntimeControlOutcome =
  | 'allowed'
  | 'blocked'
  | 'not-ready'
  | 'ready'

/**
 * Low-cardinality identity that isolates one stack-owned control plane's metrics.
 */
export interface RuntimeControlMetricIdentity {
  /** Stable control identifier injected by the owning stack. */
  readonly controlId: string
}

/**
 * Safe metadata emitted for one runtime-control decision.
 */
export interface RuntimeControlObservation {
  /** Millisecond timestamp generated by the runtime. */
  readonly observedAtMilliseconds: number
  /** Bounded result of the evaluated operation. */
  readonly outcome: RuntimeControlOutcome
  /** Immutable effective control state. */
  readonly snapshot: RuntimeControlSnapshot
  /** Stable low-cardinality execution surface. */
  readonly surface: RuntimeControlSurface
}

/**
 * Destination for one safe runtime-control observation.
 *
 * @param observation - Bounded decision metadata.
 */
export type RuntimeControlObservationRecorder = (
  observation: RuntimeControlObservation,
) => void

/**
 * Destination for one serialized Embedded Metric Format record.
 *
 * @param serializedRecord - Secret-free JSON record.
 */
export type StructuredRuntimeControlLogSink = (
  serializedRecord: string,
) => void

const UNCONFIGURED_RUNTIME_CONTROL_ID = 'unconfigured'

/**
 * Derives the metric identity from the same AppConfig target identifiers used
 * for configuration polling.
 *
 * @param applicationIdentifier - AppConfig application identifier.
 * @param configurationProfileIdentifier - AppConfig configuration profile identifier.
 * @returns Canonical identity, or undefined when either identifier is invalid.
 */
export function createRuntimeControlMetricControlId(
  applicationIdentifier: string | undefined,
  configurationProfileIdentifier: string | undefined,
): string | undefined {
  if (
    !isMetricIdentityComponent(applicationIdentifier) ||
    !isMetricIdentityComponent(configurationProfileIdentifier)
  ) {
    return undefined
  }
  return `${applicationIdentifier}:${configurationProfileIdentifier}`
}

/**
 * Binds runtime-control observations to one validated stack control identity.
 *
 * @param identity - Stack-scoped AppConfig metric identity.
 * @param sink - Optional output sink used by tests.
 * @returns Recorder that emits only the bound application's metric series.
 */
export function createRuntimeControlObservationRecorder(
  identity: RuntimeControlMetricIdentity,
  sink: StructuredRuntimeControlLogSink = writeStandardOutput,
): RuntimeControlObservationRecorder {
  const controlId = readMetricDimension(identity.controlId)
  return (observation) => {
    recordRuntimeControlObservation(
      observation,
      sink,
      { controlId },
    )
  }
}

/**
 * Writes aggregate and per-surface runtime-control metrics.
 *
 * ConfigurationFailureCount is one only for invalid documents. Intentional
 * current disabled states remain observable through DisabledCount without
 * triggering the configuration rollback alarm. Network grace is represented
 * separately by StaleCount.
 *
 * @param observation - Bounded runtime-control decision.
 * @param sink - Optional output sink used by tests.
 * @param identity - Optional application identity for the metric series.
 */
export function recordRuntimeControlObservation(
  observation: RuntimeControlObservation,
  sink: StructuredRuntimeControlLogSink = writeStandardOutput,
  identity: RuntimeControlMetricIdentity = {
    controlId: UNCONFIGURED_RUNTIME_CONTROL_ID,
  },
): void {
  const controlId = readMetricDimension(identity.controlId)
  const configurationFailure =
    observation.snapshot.status === 'invalid' ? 1 : 0
  const stale = observation.snapshot.status === 'stale' ? 1 : 0
  const providerFailure =
    observation.snapshot.status === 'unavailable' ? 1 : 0
  const blocked =
    observation.outcome === 'blocked' ||
      observation.outcome === 'not-ready'
      ? 1
      : 0
  const disabled =
    observation.snapshot.mode === 'disabled' &&
      observation.snapshot.status === 'current'
      ? 1
      : 0

  sink(JSON.stringify({
    _aws: {
      Timestamp: observation.observedAtMilliseconds,
      CloudWatchMetrics: [{
        Namespace: 'Mukuroji/RuntimeControl',
        Dimensions: [
          ['Service', 'ControlId'],
          ['Service', 'ControlId', 'Surface'],
        ],
        Metrics: [
          { Name: 'BlockedCount', Unit: 'Count' },
          { Name: 'ConfigurationFailureCount', Unit: 'Count' },
          { Name: 'DisabledCount', Unit: 'Count' },
          { Name: 'ProviderFailureCount', Unit: 'Count' },
          { Name: 'StaleCount', Unit: 'Count' },
        ],
      }],
    },
    event: 'runtime-control.evaluated',
    service: 'mukuroji-runtime-control',
    Service: 'mukuroji-runtime-control',
    controlId,
    ControlId: controlId,
    surface: observation.surface,
    Surface: observation.surface,
    outcome: observation.outcome,
    mode: observation.snapshot.mode,
    status: observation.snapshot.status,
    ...(observation.snapshot.revision === undefined
      ? {}
      : { revision: observation.snapshot.revision }),
    ...(observation.snapshot.ageMilliseconds === undefined
      ? {}
      : { ageMs: observation.snapshot.ageMilliseconds }),
    BlockedCount: blocked,
    ConfigurationFailureCount: configurationFailure,
    DisabledCount: disabled,
    ProviderFailureCount: providerFailure,
    StaleCount: stale,
  }))
}

/**
 * Normalizes an AppConfig identifier before using it as a metric dimension.
 *
 * @param value - Candidate stack-injected application identifier.
 * @returns Bounded dimension or an isolated fail-closed fallback.
 */
function readMetricDimension(value: string): string {
  const candidate = value.trim()
  return /^[A-Za-z0-9][A-Za-z0-9:_-]{0,191}$/.test(candidate)
    ? candidate
    : UNCONFIGURED_RUNTIME_CONTROL_ID
}

/**
 * Validates one delimiter-free AppConfig identifier used in a metric identity.
 *
 * @param value - Candidate application or profile identifier.
 * @returns Whether the value can be composed into a bounded identity.
 */
function isMetricIdentityComponent(
  value: string | undefined,
): value is string {
  return typeof value === 'string' &&
    /^[A-Za-z0-9][A-Za-z0-9_-]{0,90}$/.test(value)
}

/**
 * Writes one serialized observation to standard output.
 *
 * @param serializedRecord - Safe EMF record.
 */
function writeStandardOutput(serializedRecord: string): void {
  console.log(serializedRecord)
}
