/** Collaboration module public application and domain surface. */
export {
  CollaborationError,
  createProjectCollaborationEntityKey,
  createPlanningUpdateCollaborationEntityKey,
  createPlanningUpdatePublicTargetKey,
  createWorkItemCollaborationEntityKey,
  type CollaborationAutomaticWatcherCandidate,
  type CollaborationClient,
  type CollaborationComment,
  type CollaborationMemberWatcherState,
  type CollaborationNotificationCandidate,
  type CollaborationPresence,
  type CollaborationReactionEmoji,
  type CollaborationReactionInput,
  type CollaborationReactionSummary,
  type CollaborationThreadPage,
  type CollaborationWatcherReason,
  type CollaborationWatcherState,
  type PlanningUpdateTargetKeyInput,
  type CreateCollaborationCommentInput,
  type DeleteCollaborationCommentInput,
  type GetCollaborationCommentSnapshotInput,
  type GetCollaborationThreadInput,
  type GetWatcherStateInput,
  type PresenceHeartbeatInput,
  type PresenceLeaveInput,
  type ResolveCollaborationCommentInput,
  type UpdateCollaborationCommentInput,
  type UpdateWatcherInput,
  type WorkItemCollaborationScope,
} from './collaboration'
export type {
  CollaborationRealtimePublisher,
} from './application/ports/realtime-publisher'
