/** Collaboration module public application and domain surface. */
export {
  COLLABORATION_CONTEXT_BODY_MAX_LENGTH,
  COLLABORATION_CONTEXT_TITLE_MAX_LENGTH,
  CollaborationError,
  createProjectCollaborationEntityKey,
  createWorkItemCollaborationEntityKey,
  parseCuratedContextItemRow,
  type CollaborationAutomaticWatcherCandidate,
  type CollaborationClient,
  type CollaborationComment,
  type CollaborationNotificationCandidate,
  type CollaborationPresence,
  type CollaborationReactionEmoji,
  type CollaborationReactionInput,
  type CollaborationReactionSummary,
  type CollaborationThreadPage,
  type CollaborationWatcherReason,
  type CollaborationWatcherState,
  type CreateCuratedContextItemInput,
  type CreateCollaborationCommentInput,
  type CuratedContextActivitySourceAuthorizationSnapshot,
  type CuratedContextAuthorizationSnapshot,
  type CuratedContextDocumentSourceAuthorizationSnapshot,
  type CuratedContextMutationInput,
  type DeleteCollaborationCommentInput,
  type GetCollaborationCommentSnapshotInput,
  type GetCollaborationThreadInput,
  type GetCuratedContextInput,
  type GetCuratedContextMutationReplayInput,
  type GetCuratedContextRevisionsInput,
  type GetCuratedContextItemSnapshotInput,
  type GetAcceptedResolutionHistoryInput,
  type GetWatcherStateInput,
  type PresenceHeartbeatInput,
  type PresenceLeaveInput,
  type ResolveCollaborationCommentInput,
  type SetAcceptedResolutionInput,
  type UpdateCuratedContextItemInput,
  type UpdateCollaborationCommentInput,
  type UpdateWatcherInput,
  type WorkItemCollaborationScope,
} from './collaboration'
export type {
  CollaborationRealtimePublisher,
} from './application/ports/realtime-publisher'
