/** Collaboration module public application and domain surface. */
export {
  COLLABORATION_CONTEXT_BODY_MAX_LENGTH,
  COLLABORATION_CONTEXT_TITLE_MAX_LENGTH,
  CollaborationError,
  createProjectCollaborationEntityKey,
  createPlanningUpdateCollaborationEntityKey,
  createPlanningUpdatePublicTargetKey,
  createTeamIssueCommentBackfillMarkerEntityKey,
  createWorkItemCollaborationEntityKey,
  TEAM_ISSUE_COMMENT_BACKFILL_ALL_WORKSPACES,
  TEAM_ISSUE_COMMENT_BACKFILL_MARKER_RECORD_KEY,
  TEAM_ISSUE_COMMENT_BACKFILL_VERSION,
  parseCuratedContextItemRow,
  type CollaborationAutomaticWatcherCandidate,
  type CollaborationClient,
  type CollaborationComment,
  type CollaborationMemberWatcherState,
  type CollaborationNotificationCandidate,
  type CollaborationPresence,
  type CollaborationReactionEmoji,
  type CollaborationReactionInput,
  type CollaborationReactionSummary,
  type CollaborationThreadPage,
  type CollaborationWatcherReason,
  type CollaborationWatcherState,
  type BackfillCollaborationCommentInput,
  type BackfillTeamIssueCommentValidation,
  type PlanningUpdateTargetKeyInput,
  type CreateCuratedContextItemInput,
  type CreateCollaborationCommentInput,
  type CuratedContextActivitySourceAuthorizationSnapshot,
  type CuratedContextAuthorizationSnapshot,
  type CuratedContextDocumentSourceAuthorizationSnapshot,
  type CuratedContextMutationInput,
  type DeleteCollaborationCommentInput,
  type GetCollaborationCommentMutationReplayInput,
  type GetCollaborationCommentSnapshotInput,
  type GetCollaborationThreadInput,
  type GetCuratedContextInput,
  type GetCuratedContextMutationReplayInput,
  type GetCuratedContextRevisionsInput,
  type GetCuratedContextItemSnapshotInput,
  type GetAcceptedResolutionHistoryInput,
  type GetWatcherStateInput,
  type PresenceHeartbeatInput,
  type PresenceLeaveInput,
  type ResolveCollaborationCommentInput,
  type SetAcceptedResolutionInput,
  type UpdateCuratedContextItemInput,
  type UpdateCollaborationCommentInput,
  type UpdateWatcherInput,
  type WorkItemCollaborationScope,
} from './collaboration'
export type {
  CollaborationRealtimePublisher,
} from './application/ports/realtime-publisher'
