/** Workspace Search module public application and domain surface. */
export {
  WorkspaceSearchError,
  createCommentWorkspaceSearchEntityId,
  createCommentWorkspaceSearchDocument,
  createCuratedContextItemWorkspaceSearchDocument,
  createDocumentWorkspaceSearchBody,
  createDocumentWorkspaceSearchDocument,
  createDocumentWorkspaceSearchSourceDocument,
  createProjectWorkspaceSearchDocument,
  createSavedWorkspaceViewRecordKey,
  createTaskViewProjectScopeKey,
  createTaskViewRecordKey,
  createTaskViewStatusKey,
  createTeamWorkspaceSearchDocument,
  createWorkItemWorkspaceSearchDocument,
  createWorkspaceSearchDocument,
  createWorkspaceSearchDocumentRecordKey,
  createWorkspaceSearchProjectionDigest,
  ensureLocalWorkspaceSearchTable,
  migrateSavedWorkspaceView,
  readWorkspaceSearchDocument,
  type CreateSavedWorkspaceViewRequest,
  type CreateTaskViewRequest,
  type DeleteSavedWorkspaceViewRequest,
  type DeleteTaskViewRequest,
  type DuplicateTaskViewRequest,
  type GetTaskViewRequest,
  type ListSavedWorkspaceViewsInput,
  type ListTaskViewsInput,
  type ResolveTaskViewRelationIdsInput,
  type SavedViewAccessScope,
  type TaskViewAccessScope,
  type TaskViewClient,
  type UpdateTaskViewRequest,
  type UpdateSavedWorkspaceViewRequest,
  type WorkspaceSearchAccessScope,
  type WorkspaceSearchClient,
  type WorkspaceSearchDocument,
  type WorkspaceSearchQueryInput,
  type WorkspaceSearchResolvedScope,
} from './workspace-search'
