import {
  createTranslator,
  type Locale,
} from '../../shared/i18n/i18n'
import type { PlanningLabels } from './PlanningScreen'
import { formatPlanningUpdateDate } from '../model/date'

/**
 * PlanningScreen へ渡す locale 済み label を生成します。
 *
 * @param locale - 表示 locale です。
 * @returns Planning UI が必要とする label 一式です。
 */
export function createPlanningLabels(locale: Locale): PlanningLabels {
  const t = createTranslator(locale)
  return {
    eyebrow: t('planning.eyebrow'),
    title: t('planning.title'),
    description: t('planning.description'),
    viewTabs: t('planning.title'),
    timeline: t('planning.view.timeline'),
    roadmap: t('planning.view.roadmap'),
    portfolio: t('planning.view.portfolio'),
    loading: t('planning.loading'),
    error: t('planning.error'),
    retry: t('planning.action.retry'),
    emptyTitle: t('planning.empty.title'),
    emptyDescription: t('planning.empty.description'),
    timelineTitle: t('planning.view.timeline'),
    timelineDescription: t('planning.description'),
    baseline: t('planning.field.baselineStart'),
    forecast: t('planning.field.forecastEnd'),
    progress: t('planning.field.progress'),
    owner: t('planning.field.owner'),
    health: t('planning.field.health'),
    risk: t('planning.field.risk'),
    status: t('planning.field.status'),
    linkedWorkItems: t('planning.section.workItems'),
    criticalPath: t('planning.section.criticalPath'),
    criticalPathDays: (days) => `${t('planning.section.criticalPath')}: ${days}`,
    slackDays: (days) => `${t('planning.field.slackDays')}: ${days}`,
    percent: (value) => `${value}%`,
    workItemCount: (count) => `${count} ${t('planning.section.workItems')}`,
    milestoneEditor: t('planning.type.milestone'),
    milestoneDate: t('planning.field.forecastEnd'),
    save: t('planning.action.save'),
    dependencyEditor: t('planning.action.addDependency'),
    predecessor: t('planning.field.predecessor'),
    successor: t('planning.field.successor'),
    dependencyType: t('planning.field.type'),
    dependencyLag: t('planning.field.lagDays'),
    addDependency: t('planning.action.addDependency'),
    cycleRollover: t('planning.action.rollover'),
    sourceCycle: t('planning.section.cycles'),
    targetCycle: t('planning.field.targetCycle'),
    rollover: t('planning.action.rollover'),
    closedCycleRollover: t('planning.rollover.closedSource'),
    noRolloverTarget: t('planning.rollover.noTarget'),
    capacity: (value) => `${t('planning.field.capacity')}: ${value}`,
    roadmapTitle: t('planning.section.hierarchy'),
    roadmapDescription: t('planning.description'),
    goalWorkItems: t('planning.section.workItems'),
    noGoalWorkItems: t('tasks.empty'),
    openWorkItem: t('workspace.action.openTask'),
    entityActions: t('planning.title'),
    archive: t('planning.action.archive'),
    duplicateId: t('planning.field.id'),
    duplicate: t('planning.action.duplicate'),
    moveTarget: t('planning.field.parent'),
    moveToRoot: t('issues.project.unassigned'),
    move: t('planning.action.move'),
    readOnly: t('planning.readOnly'),
    portfolioTitle: t('planning.view.portfolio'),
    portfolioDescription: t('planning.description'),
    entity: t('planning.field.title'),
    entityId: t('planning.field.id'),
    entityType: t('planning.field.entityType'),
    team: t('planning.field.team'),
    project: t('planning.field.project'),
    startDate: t('planning.field.baselineStart'),
    endDate: t('planning.field.baselineEnd'),
    createEntity: t('planning.action.create'),
    create: t('planning.action.create'),
    cadenceWeek: t('planning.cadence.week'),
    cadenceMonth: t('planning.cadence.month'),
    carryOverMove: t('planning.carryOver.move-incomplete'),
    carryOverKeep: t('planning.carryOver.keep-incomplete'),
    statusUpdate: t('planning.section.statusUpdates'),
    statusMessage: t('planning.field.statusMessage'),
    addStatusUpdate: t('planning.action.addStatusUpdate'),
    updateState: t('planning.field.updateState'),
    latestUpdate: t('planning.field.latestUpdate'),
    nextDueAt: t('planning.field.nextDueAt'),
    neverUpdated: t('planning.updateState.neverUpdated'),
    noDueDate: t('planning.updateState.noDueDate'),
    projectTarget: t('planning.type.project'),
    initiativeTarget: t('planning.type.initiative'),
    freshnessValues: {
      'not-configured': t('planning.updateState.not-configured'),
      missing: t('planning.updateState.missing'),
      current: t('planning.updateState.current'),
      overdue: t('planning.updateState.overdue'),
      stale: t('planning.updateState.stale'),
    },
    dueAtMeta: (nextDueAt, timeZone) => {
      const formattedDate = formatPlanningUpdateDate(nextDueAt, timeZone, locale)
      const dueLabel = t('planning.updateState.dueMeta').replace('{date}', formattedDate)
      return timeZone ? `${dueLabel} · ${timeZone}` : dueLabel
    },
    cadenceTitle: t('planning.section.updateCadence'),
    cadenceDescription: t('planning.section.updateCadence.description'),
    updateOwner: t('planning.field.updateOwner'),
    updateCadence: t('planning.field.updateCadence'),
    timeZone: t('planning.field.timeZone'),
    reminder: t('planning.field.reminder'),
    escalation: t('planning.field.escalation'),
    escalationOwner: t('planning.field.escalationOwner'),
    saveCadence: t('planning.action.saveCadence'),
    clearCadence: t('planning.action.clearCadence'),
    cadenceDisabled: t('planning.updateCadence.disabled'),
    composerTitle: t('planning.section.updateComposer'),
    composerDescription: t('planning.section.updateComposer.description'),
    composerRequiredHint: t('planning.updateComposer.requiredHint'),
    formInvalid: t('planning.form.invalid'),
    summary: t('planning.field.summary'),
    progressSnapshot: t('planning.field.progressSnapshot'),
    riskSummary: t('planning.field.riskUpdate'),
    decisionSummary: t('planning.field.decision'),
    helpNeeded: t('planning.field.helpNeeded'),
    nextAction: t('planning.field.nextAction'),
    evidence: t('planning.field.evidence'),
    evidenceType: t('planning.updateEvidence.type'),
    evidenceNone: t('planning.updateEvidence.none'),
    evidenceWorkItem: t('planning.updateEvidence.workItem'),
    evidencePlanningEntity: t('planning.updateEvidence.planningEntity'),
    evidenceFile: t('planning.updateEvidence.file'),
    evidenceLink: t('planning.updateEvidence.link'),
    evidenceWorkItemPlaceholder: t('planning.updateEvidence.workItemPlaceholder'),
    evidencePlanningEntityPlaceholder: t('planning.updateEvidence.planningEntityPlaceholder'),
    evidenceFileIdPlaceholder: t('planning.updateEvidence.fileIdPlaceholder'),
    evidenceLabelPlaceholder: t('planning.updateEvidence.labelPlaceholder'),
    evidenceUrlPlaceholder: t('planning.updateEvidence.urlPlaceholder'),
    publishUpdate: t('planning.action.publishStatusUpdate'),
    historyTitle: t('planning.section.updateHistory'),
    historyDescription: t('planning.section.updateHistory.description'),
    noStatusUpdatesDescription: t('planning.statusUpdates.emptyDescription'),
    immutable: t('planning.updateHistory.immutable'),
    historyLoading: t('planning.updateHistory.loading'),
    historyError: t('planning.updateHistory.error'),
    retryHistory: t('planning.action.retry'),
    loadMoreHistory: t('planning.action.loadMoreHistory'),
    loadingMoreHistory: t('planning.updateHistory.loadingMore'),
    comparePrevious: t('planning.action.comparePrevious'),
    previous: t('planning.updateHistory.previous'),
    current: t('planning.updateHistory.current'),
    changeLabels: {
      health: t('planning.field.health'),
      risk: t('planning.field.risk'),
      progress: t('planning.field.progress'),
      milestones: t('planning.updateHistory.change.milestone'),
      dependencies: t('planning.updateHistory.change.dependency'),
      scope: t('planning.updateHistory.change.scope'),
      'target-date': t('planning.updateHistory.change.targetDate'),
    },
    progressPercent: (value) => `${value}%`,
    commentCount: (count) => `${t('planning.field.comment')}: ${count}`,
    watchUpdates: t('planning.action.watchUpdates'),
    watchingUpdates: t('planning.action.watchingUpdates'),
    exportHistory: t('planning.action.exportHistory'),
    addComment: t('planning.action.addComment'),
    commentPlaceholder: t('planning.field.commentPlaceholder'),
    reaction: t('planning.field.reaction'),
    watcherCount: (count) => t('planning.field.watcherCount').replace(
      '{count}',
      String(count),
    ),
    collaborationLoading: t('planning.updateCollaboration.loading'),
    collaborationError: t('planning.updateCollaboration.error'),
    workItemLinkEditor: t('planning.action.linkWorkItem'),
    workItem: t('planning.section.workItems'),
    cycle: t('planning.type.cycle'),
    milestone: t('planning.type.milestone'),
    goal: t('planning.type.goal'),
    goalFramework: t('planning.field.goalFramework'),
    linkWorkItem: t('planning.action.linkWorkItem'),
    unlinkWorkItem: t('planning.action.unlinkWorkItem'),
    deleteDependency: t('planning.action.delete'),
    reportedHealth: t('planning.field.reportedHealth'),
    rollupHealth: t('planning.field.rollupHealth'),
    noStatusUpdates: t('planning.statusUpdates.empty'),
    statusUpdateMeta: (authorMemberKey, createdAt) =>
      `${authorMemberKey} · ${formatPlanningUpdateDate(createdAt, undefined, locale)}`,
    entityTypes: {
      cycle: t('planning.type.cycle'),
      milestone: t('planning.type.milestone'),
      release: t('planning.type.release'),
      phase: t('planning.type.phase'),
      goal: t('planning.type.goal'),
      initiative: t('planning.type.initiative'),
      roadmap: t('planning.type.roadmap'),
      portfolio: t('planning.type.portfolio'),
    },
    statuses: {
      proposed: t('planning.status.proposed'),
      planned: t('planning.status.planned'),
      active: t('planning.status.active'),
      paused: t('planning.status.paused'),
      completed: t('planning.status.completed'),
      canceled: t('planning.status.canceled'),
    },
    healthValues: {
      unknown: t('planning.health.unknown'),
      'on-track': t('planning.health.on-track'),
      'at-risk': t('planning.health.at-risk'),
      'off-track': t('planning.health.off-track'),
    },
    riskValues: {
      none: t('planning.risk.none'),
      low: t('planning.risk.low'),
      medium: t('planning.risk.medium'),
      high: t('planning.risk.high'),
      critical: t('planning.risk.critical'),
    },
    dependencyTypes: {
      'finish-to-start': t('planning.dependency.finish-to-start'),
      'start-to-start': t('planning.dependency.start-to-start'),
      'finish-to-finish': t('planning.dependency.finish-to-finish'),
      'start-to-finish': t('planning.dependency.start-to-finish'),
    },
    workItemDependencyT: t,
    goalFrameworkValues: {
      goal: t('planning.goalFramework.goal'),
      objective: t('planning.goalFramework.objective'),
      'key-result': t('planning.goalFramework.key-result'),
    },
  }
}
