import type { Context, Hono, MiddlewareHandler } from 'hono'
import { cors } from 'hono/cors'
import { HTTPException } from 'hono/http-exception'
import type {
  ApiAccessObservation,
  ApiErrorObservation,
  ApiRuntimeMetadata,
} from '../../infrastructure/observability/api-observability'
import {
  classifyApiError,
  isEligibleApiSliRequest,
  resolveApiRuntimeMetadata,
  summarizeApiMethod,
  summarizeApiRoute,
} from '../../infrastructure/observability/api-observability'

/**
 * Server-generated identifiers bound to one HTTP request.
 */
interface CanonicalRequestIdentifiers {
  /** Correlation identifier generated by this API boundary. */
  readonly correlationId: string
  /** Hop-local request identifier generated by this API boundary. */
  readonly requestId: string
}

const identifiersByRequest = new WeakMap<
  Request,
  CanonicalRequestIdentifiers
>()

/**
 * API 共通 middleware の組み立てに必要な依存です。
 */
export interface CommonMiddlewareDependencies {
  /** 現在許可されている browser origin を返します。 */
  getAllowedOrigins(): readonly string[]
  /**
   * Generates a locally unique server-controlled request identifier.
   *
   * @returns A request-safe opaque identifier.
   */
  createIdentifier(): string
  /**
   * Returns the current millisecond timestamp for duration measurements.
   *
   * @returns The current Unix timestamp in milliseconds.
   */
  now(): number
  /**
   * Records a safe structured request completion event.
   *
   * @param observation - Redacted request completion metadata.
   */
  recordAccess(observation: ApiAccessObservation): void
  /**
   * Records a safe structured unexpected-error event.
   *
   * @param observation - Redacted unexpected-error metadata.
   */
  recordError(observation: ApiErrorObservation): void
}

/**
 * Registers correlation, structured observability, CORS, and cache middleware.
 *
 * @param app - Hono application receiving the common middleware.
 * @param dependencies - Operational and security dependencies.
 */
export function registerCommonMiddleware(
  app: Hono,
  dependencies: CommonMiddlewareDependencies,
): void {
  app.use('/api/*', async (context, next) => {
    const startedAt = dependencies.now()
    const identifiers = createCanonicalRequestIdentifiers(
      dependencies.createIdentifier,
    )
    const sliEligible = isEligibleApiSliRequest(
      context.req.method,
      context.req.path,
    )
    const method = summarizeApiMethod(context.req.method)
    const routeGroup = summarizeApiRoute(context.req.path)
    const runtimeMetadata = resolveApiRuntimeMetadata(context.env)

    identifiersByRequest.set(context.req.raw, identifiers)
    context.req.raw.headers.set(
      'X-Correlation-Id',
      identifiers.correlationId,
    )
    context.req.raw.headers.set('X-Request-Id', identifiers.requestId)

    try {
      await next()
    } catch (error) {
      if (error instanceof Error) throw error
      recordUnexpectedApiError(
        dependencies,
        identifiers,
        runtimeMetadata,
        method,
        routeGroup,
        error,
      )
      context.res = createInternalErrorResponse(
        context,
        identifiers.correlationId,
      )
    }

    const completedAt = dependencies.now()
    context.header('X-Correlation-Id', identifiers.correlationId)
    context.header('X-Request-Id', identifiers.requestId)
    dependencies.recordAccess({
      correlationId: identifiers.correlationId,
      durationMilliseconds: Math.max(0, completedAt - startedAt),
      method,
      observedAtMilliseconds: completedAt,
      requestId: identifiers.requestId,
      routeGroup,
      sliEligible,
      ...runtimeMetadata,
      status: context.res.status,
    })
  })

  app.onError((error, context) => {
    if (error instanceof HTTPException) return error.getResponse()

    const identifiers = identifiersByRequest.get(context.req.raw) ??
      createCanonicalRequestIdentifiers(
      dependencies.createIdentifier,
    )
    const method = summarizeApiMethod(context.req.method)
    const routeGroup = summarizeApiRoute(context.req.path)
    const runtimeMetadata = resolveApiRuntimeMetadata(context.env)

    recordUnexpectedApiError(
      dependencies,
      identifiers,
      runtimeMetadata,
      method,
      routeGroup,
      error,
    )
    context.header('X-Correlation-Id', identifiers.correlationId)
    context.header('X-Request-Id', identifiers.requestId)
    return createInternalErrorResponse(context, identifiers.correlationId)
  })

  app.use(
    '/api/*',
    cors({
      origin: (origin) =>
        dependencies.getAllowedOrigins().includes(origin)
          ? origin
          : undefined,
      allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
      allowHeaders: [
        'Authorization',
        'Content-Type',
        'Idempotency-Key',
        'X-Break-Glass-Reason',
        'X-Correlation-Id',
        'X-Request-Id',
      ],
      exposeHeaders: [
        'X-Audit-Truncated',
        'X-Audit-Next-Cursor',
        'X-Correlation-Id',
        'X-Request-Id',
      ],
    }),
  )

  app.use('/api/*', async (context, next) => {
    await next()
    if (
      context.req.path === '/api/ready' ||
      context.req.path.startsWith('/api/request-') ||
      context.req.path.startsWith('/api/enterprise/security') ||
      context.req.path.startsWith('/api/auth/sso') ||
      context.req.path.startsWith('/api/scim/')
    ) {
      context.header('Cache-Control', 'private, no-store')
      context.header('Pragma', 'no-cache')
      context.header('Referrer-Policy', 'no-referrer')
    }
  })
}

/**
 * Reads the server-generated correlation identifier established by common middleware.
 *
 * @param request - Raw request used as the weakly referenced lookup key.
 * @returns Canonical correlation identifier, or undefined when common middleware is absent.
 */
export function readCanonicalCorrelationId(
  request: Request,
): string | undefined {
  return identifiersByRequest.get(request)?.correlationId
}

/**
 * Registers the rejection-audit middleware after admission controls.
 *
 * Keeping this registration separate lets the runtime-control gate return
 * before authentication or persistence-backed audit work begins.
 *
 * @param app - Hono application receiving security-audit middleware.
 * @param middleware - Enterprise mutation rejection-audit middleware.
 */
export function registerEnterpriseSecurityAuditMiddleware(
  app: Hono,
  middleware: MiddlewareHandler,
): void {
  app.use('/api/enterprise/security/*', middleware)
  app.use('/api/scim/*', middleware)
}

/**
 * Creates canonical identifiers without consulting untrusted request headers.
 *
 * @param createIdentifier - Server-controlled opaque identifier factory.
 * @returns Canonical request identifiers for propagation and logging.
 */
function createCanonicalRequestIdentifiers(
  createIdentifier: () => string,
): CanonicalRequestIdentifiers {
  return Object.freeze({
    correlationId: createIdentifier(),
    requestId: createIdentifier(),
  })
}

/**
 * Records one bounded unexpected API failure.
 *
 * @param dependencies - Structured error observation destination and clock.
 * @param identifiers - Server-generated request identifiers.
 * @param runtimeMetadata - Trusted Lambda and X-Ray join metadata.
 * @param method - Bounded HTTP method category.
 * @param routeGroup - Bounded route group.
 * @param error - Unknown thrown value.
 */
function recordUnexpectedApiError(
  dependencies: CommonMiddlewareDependencies,
  identifiers: CanonicalRequestIdentifiers,
  runtimeMetadata: ApiRuntimeMetadata,
  method: string,
  routeGroup: string,
  error: unknown,
): void {
  dependencies.recordError({
    correlationId: identifiers.correlationId,
    errorType: classifyApiError(error),
    method,
    observedAtMilliseconds: dependencies.now(),
    requestId: identifiers.requestId,
    routeGroup,
    ...runtimeMetadata,
  })
}

/**
 * Creates the stable safe response used for unexpected API failures.
 *
 * @param context - Hono request context.
 * @param correlationId - Server-generated correlation identifier.
 * @returns A generic correlated HTTP 500 response.
 */
function createInternalErrorResponse(
  context: Context,
  correlationId: string,
): Response {
  return context.json({
    code: 'InternalError',
    correlationId,
    message: 'The request could not be completed.',
  }, 500)
}
