/** Audit module public application and domain surface. */
export {
  AUDIT_ACTOR_INDEX_NAME,
  AUDIT_ENTITY_INDEX_NAME,
  AUDIT_MAX_TEXT_LENGTH,
  AUDIT_REDACTED_VALUE,
  AUDIT_SCHEMA_VERSION,
  AUDIT_TARGET_INDEX_NAME,
  AUDIT_UNKNOWN_OCCURRED_AT,
  AUDIT_WORKSPACE_INDEX_NAME,
  DynamoDbAuditEventsClient,
  WORKSPACE_ACCESS_AUDIT_ENTITY_ID_CONTRACT_VERSION,
  calculateAuditExpiresAt,
  createAuditActorKey,
  createAuditConsumerReceiptTransactPut,
  createAuditEntityKey,
  createAuditEvent,
  createAuditEventId,
  createAuditEventTransactPut,
  createAuditFieldChanges,
  createAuditFieldDiff,
  createAuditTransactPut,
  createMutationAuditContext,
  createMutationAuditEventPut,
  createRequestFingerprint,
  createWorkspaceInvitationAuditEntityId,
  createWorkspaceMemberAuditEntityId,
  createWorkspaceMemberAuditEntityIdFromKeyBytes,
  ensureLocalAuditEventsTable,
  getConfiguredAuditRetentionDays,
  getConfiguredAuditTableName,
  getConfiguredDynamoDbEndpoint,
  readWorkspaceAuditPseudonymKey,
  toAuditEventView,
  normalizeAuditEvent,
  type AuditActor,
  type AuditActorKind,
  type AuditConsumerReceiptInput,
  type AuditDiffOptions,
  type AuditEventEntityType,
  type AuditEventPage,
  type AuditEventQuery,
  type AuditEventV1,
  type AuditFieldChange,
  type AuditIndexNames,
  type AuditObject,
  type AuditOutboxStatus,
  type AuditRequestFingerprintInput,
  type AuditSource,
  type AuditSourceKind,
  type AuditTransactWriteItem,
  type AuditValue,
  type CreateAuditEventInput,
  type LocalAuditTableBootstrapOptions,
  type MutationAuditContext,
  type MutationAuditContextInput,
  type MutationAuditEventInput,
} from './audit'
