import {
  createDefaultDueDateWorkItemSchedule,
  PLANNING_SCHEMA_VERSION,
  PLANNING_UPDATE_CONTENT_VERSION,
  type PlanningSnapshot,
  type PlanningUpdate,
} from '@mukuroji/contracts'

/**
 * Planning 画面の Story と test で共有する整合した snapshot です。
 */
export const planningSnapshotFixture = {
  schemaVersion: PLANNING_SCHEMA_VERSION,
  revision: 12,
  updatedAt: '2026-07-16T03:00:00.000Z',
  entities: [
    {
      id: 'portfolio-product',
      type: 'portfolio',
      title: 'Product portfolio',
      description: 'Customer-facing product investments.',
      ownerMemberKey: 'owner@example.com',
      status: 'active',
      health: 'on-track',
      rollupHealth: 'at-risk',
      risk: 'medium',
      progressMode: 'automatic',
      progress: 58,
      linkedWorkItemCount: 3,
      baseline: { startDate: '2026-07-01', endDate: '2026-09-30' },
      forecast: { startDate: '2026-07-01', endDate: '2026-10-09' },
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'roadmap-growth',
      type: 'roadmap',
      title: 'Growth roadmap',
      parentId: 'portfolio-product',
      ownerMemberKey: 'owner@example.com',
      status: 'active',
      health: 'on-track',
      rollupHealth: 'at-risk',
      risk: 'medium',
      progressMode: 'automatic',
      progress: 58,
      linkedWorkItemCount: 3,
      baseline: { startDate: '2026-07-01', endDate: '2026-09-30' },
      forecast: { startDate: '2026-07-01', endDate: '2026-10-09' },
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'initiative-onboarding',
      type: 'initiative',
      title: 'Onboarding acceleration',
      parentId: 'roadmap-growth',
      teamId: 'core-team',
      ownerMemberKey: 'lead@example.com',
      status: 'active',
      health: 'at-risk',
      rollupHealth: 'at-risk',
      risk: 'high',
      progressMode: 'automatic',
      progress: 58,
      linkedWorkItemCount: 3,
      baseline: { startDate: '2026-07-01', endDate: '2026-09-15' },
      forecast: { startDate: '2026-07-03', endDate: '2026-09-28' },
      statusUpdates: [
        {
          id: 'update-initiative-1',
          message: 'Research is complete; implementation risk remains.',
          authorMemberKey: 'lead@example.com',
          health: 'at-risk',
          risk: 'high',
          createdAt: '2026-07-15T09:00:00.000Z',
        },
      ],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'goal-activation',
      type: 'goal',
      title: 'Improve first-week activation',
      parentId: 'initiative-onboarding',
      teamId: 'core-team',
      ownerMemberKey: 'lead@example.com',
      status: 'active',
      health: 'at-risk',
      rollupHealth: 'at-risk',
      risk: 'high',
      progressMode: 'automatic',
      progress: 50,
      linkedWorkItemCount: 2,
      baseline: { startDate: '2026-07-01', endDate: '2026-08-31' },
      forecast: { startDate: '2026-07-03', endDate: '2026-09-07' },
      goalFramework: 'objective',
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'phase-build',
      type: 'phase',
      title: 'Build onboarding journey',
      parentId: 'initiative-onboarding',
      teamId: 'core-team',
      projectId: 'refero',
      ownerMemberKey: 'builder@example.com',
      status: 'active',
      health: 'on-track',
      rollupHealth: 'on-track',
      risk: 'low',
      progressMode: 'manual',
      manualProgress: 60,
      progress: 60,
      linkedWorkItemCount: 2,
      baseline: { startDate: '2026-07-07', endDate: '2026-08-14' },
      forecast: { startDate: '2026-07-07', endDate: '2026-08-18' },
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'milestone-beta',
      type: 'milestone',
      title: 'Beta ready',
      parentId: 'initiative-onboarding',
      teamId: 'core-team',
      projectId: 'refero',
      ownerMemberKey: 'lead@example.com',
      status: 'planned',
      health: 'at-risk',
      rollupHealth: 'at-risk',
      risk: 'high',
      progressMode: 'automatic',
      progress: 50,
      linkedWorkItemCount: 2,
      baseline: { startDate: '2026-08-21', endDate: '2026-08-21' },
      forecast: { startDate: '2026-08-28', endDate: '2026-08-28' },
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'release-autumn',
      type: 'release',
      title: 'Autumn release',
      parentId: 'roadmap-growth',
      ownerMemberKey: 'owner@example.com',
      status: 'planned',
      health: 'on-track',
      rollupHealth: 'on-track',
      risk: 'medium',
      progressMode: 'automatic',
      progress: 30,
      linkedWorkItemCount: 1,
      baseline: { startDate: '2026-09-15', endDate: '2026-09-30' },
      forecast: { startDate: '2026-09-24', endDate: '2026-10-09' },
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'cycle-14',
      type: 'cycle',
      title: 'Cycle 14',
      teamId: 'core-team',
      ownerMemberKey: 'lead@example.com',
      status: 'active',
      health: 'on-track',
      rollupHealth: 'on-track',
      risk: 'low',
      progressMode: 'automatic',
      progress: 50,
      linkedWorkItemCount: 2,
      baseline: { startDate: '2026-07-13', endDate: '2026-07-26' },
      forecast: { startDate: '2026-07-13', endDate: '2026-07-26' },
      cadence: { unit: 'week', count: 2 },
      capacity: 20,
      carryOverPolicy: 'move-incomplete',
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
    {
      id: 'cycle-15',
      type: 'cycle',
      title: 'Cycle 15',
      teamId: 'core-team',
      ownerMemberKey: 'lead@example.com',
      status: 'planned',
      health: 'unknown',
      rollupHealth: 'unknown',
      risk: 'none',
      progressMode: 'automatic',
      progress: 0,
      linkedWorkItemCount: 0,
      baseline: { startDate: '2026-07-27', endDate: '2026-08-09' },
      forecast: { startDate: '2026-07-27', endDate: '2026-08-09' },
      cadence: { unit: 'week', count: 2 },
      capacity: 20,
      carryOverPolicy: 'move-incomplete',
      statusUpdates: [],
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
  ],
  dependencies: [
    {
      id: 'dependency-build-beta',
      predecessorId: 'phase-build',
      successorId: 'milestone-beta',
      type: 'finish-to-start',
      lagDays: 2,
      createdAt: '2026-07-10T00:00:00.000Z',
    },
    {
      id: 'dependency-beta-release',
      predecessorId: 'milestone-beta',
      successorId: 'release-autumn',
      type: 'finish-to-start',
      lagDays: 1,
      createdAt: '2026-07-10T00:00:00.000Z',
    },
  ],
  workItemDependencies: [
    {
      id: 'work-item-dependency-copy-events',
      predecessor: { teamId: 'core-team', workItemId: 'journey-copy' },
      successor: { teamId: 'core-team', workItemId: 'journey-events' },
      type: 'finish-to-finish',
      lagDays: 1,
      constraint: {
        anchor: 'finish',
        kind: 'not-before',
        date: '2026-07-23',
      },
      createdAt: '2026-07-12T00:00:00.000Z',
      updatedAt: '2026-07-16T03:00:00.000Z',
    },
  ],
  workItemLinks: [
    {
      teamId: 'core-team',
      workItemId: 'journey-copy',
      projectId: 'refero',
      cycleId: 'cycle-14',
      milestoneId: 'milestone-beta',
      goalIds: ['goal-activation'],
      createdAt: '2026-07-12T00:00:00.000Z',
    },
    {
      teamId: 'core-team',
      workItemId: 'journey-events',
      projectId: 'refero',
      cycleId: 'cycle-14',
      milestoneId: 'milestone-beta',
      goalIds: ['goal-activation'],
      createdAt: '2026-07-12T00:00:00.000Z',
    },
  ],
  workItems: [
    {
      id: 'journey-copy',
      revision: 3,
      teamId: 'core-team',
      title: 'Finalize onboarding copy',
      projectId: 'refero',
      statusCategory: 'started',
      dueDate: '2026-07-22',
      schedule: createDefaultDueDateWorkItemSchedule('2026-07-22'),
    },
    {
      id: 'journey-events',
      revision: 2,
      teamId: 'core-team',
      title: 'Instrument activation events',
      projectId: 'refero',
      statusCategory: 'unstarted',
      dueDate: '2026-07-25',
      schedule: createDefaultDueDateWorkItemSchedule('2026-07-25'),
    },
  ],
  updateTargets: [
    {
      target: { type: 'project', teamId: 'core-team', projectId: 'refero' },
      cadence: {
        updateOwnerMemberKey: 'builder@example.com',
        cadence: { unit: 'week', count: 1 },
        timeZone: 'Asia/Tokyo',
        nextDueAt: '2026-07-18T00:00:00.000Z',
        reminderHoursBefore: 24,
        escalationHoursAfter: 12,
        escalationMemberKey: 'lead@example.com',
      },
      updateState: 'overdue',
      latestVersion: 1,
      latestUpdate: {
        id: 'update-project-refero-1',
        version: 1,
        health: 'on-track',
        risk: 'low',
        summary: 'Implementation is progressing against the current milestone.',
        progressSnapshot: { percent: 60, linkedWorkItemCount: 2 },
        authorMemberKey: 'builder@example.com',
        coveredDueAt: '2026-07-11T00:00:00.000Z',
        createdAt: '2026-07-11T02:00:00.000Z',
      },
      updatedAt: '2026-07-11T02:00:00.000Z',
    },
    {
      target: { type: 'initiative', entityId: 'initiative-onboarding' },
      cadence: {
        updateOwnerMemberKey: 'lead@example.com',
        cadence: { unit: 'week', count: 1 },
        timeZone: 'Asia/Tokyo',
        nextDueAt: '2026-07-22T00:00:00.000Z',
        reminderHoursBefore: 24,
        escalationHoursAfter: 24,
        escalationMemberKey: 'owner@example.com',
      },
      updateState: 'current',
      latestVersion: 2,
      latestUpdate: {
        id: 'update-initiative-2',
        version: 2,
        health: 'at-risk',
        risk: 'high',
        summary: 'Research is complete; implementation risk remains.',
        progressSnapshot: { percent: 58, linkedWorkItemCount: 3 },
        authorMemberKey: 'lead@example.com',
        coveredDueAt: '2026-07-15T00:00:00.000Z',
        createdAt: '2026-07-15T09:00:00.000Z',
      },
      updatedAt: '2026-07-15T09:00:00.000Z',
    },
  ],
  criticalPath: {
    entityIds: ['phase-build', 'milestone-beta', 'release-autumn'],
    totalDurationDays: 96,
    slackByEntityId: {
      'phase-build': 0,
      'milestone-beta': 0,
      'release-autumn': 0,
    },
  },
  workItemDependencySummary: {
    criticalPath: {
      workItems: [
        { teamId: 'core-team', workItemId: 'journey-copy' },
        { teamId: 'core-team', workItemId: 'journey-events' },
      ],
      totalDurationDays: 4,
      slackByWorkItemKey: {
        'core-team/journey-copy': 0,
        'core-team/journey-events': 0,
      },
    },
    conflicts: [],
    unresolvedBlockerCount: 1,
    affectedProjects: [{ projectId: 'refero', teamId: 'core-team' }],
    affectedProjectIds: ['refero'],
    affectedMilestoneIds: ['milestone-beta'],
  },
} satisfies PlanningSnapshot

/** Immutable structured update history used by detail-pane stories and tests. */
export const planningUpdateHistoryFixture = [
  {
    id: 'update-initiative-2',
    target: { type: 'initiative', entityId: 'initiative-onboarding' },
    version: 2,
    contentVersion: PLANNING_UPDATE_CONTENT_VERSION,
    origin: 'manual',
    health: 'at-risk',
    risk: 'high',
    summary: 'Research is complete; implementation risk remains.',
    riskSummary: 'The instrumentation path still depends on the analytics schema review.',
    decisionSummary: 'Keep the beta milestone and narrow the first cohort.',
    helpNeeded: 'Analytics review by Friday.',
    nextAction: 'Finish event instrumentation and validate the beta cohort.',
    progressSnapshot: { percent: 58, linkedWorkItemCount: 3 },
    contextSnapshot: {
      health: 'at-risk',
      risk: 'high',
      progress: { percent: 58, linkedWorkItemCount: 3 },
      scope: { teamId: 'core-team' },
      targetDate: '2026-09-28',
      milestones: [{
        entityId: 'milestone-beta',
        title: 'Beta ready',
        status: 'planned',
        forecast: { startDate: '2026-08-28', endDate: '2026-08-28' },
      }],
      dependencies: [{
        dependencyId: 'dependency-build-beta',
        predecessorId: 'phase-build',
        successorId: 'milestone-beta',
        type: 'finish-to-start',
        lagDays: 2,
      }],
    },
    changes: [
      { type: 'progress', before: 42, after: 58 },
      { type: 'target-date', before: '2026-09-21', after: '2026-09-28' },
      {
        type: 'dependencies',
        addedIds: ['dependency-build-beta'],
        removedIds: [],
        changedIds: [],
      },
    ],
    evidence: [
      { type: 'work-item', teamId: 'core-team', workItemId: 'journey-events' },
      { type: 'planning-entity', entityId: 'milestone-beta' },
      {
        type: 'decision',
        decisionId: 'decision-beta-cohort',
        url: 'https://example.com/decisions/decision-beta-cohort',
      },
      {
        type: 'file',
        fileId: 'research-findings.pdf',
        url: 'https://example.com/files/research-findings.pdf',
      },
      { type: 'link', url: 'https://example.com/research', label: 'Research findings' },
    ],
    authorMemberKey: 'lead@example.com',
    coveredDueAt: '2026-07-15T00:00:00.000Z',
    createdAt: '2026-07-15T09:00:00.000Z',
  },
  {
    id: 'update-initiative-1',
    target: { type: 'initiative', entityId: 'initiative-onboarding' },
    version: 1,
    contentVersion: PLANNING_UPDATE_CONTENT_VERSION,
    origin: 'manual',
    health: 'on-track',
    risk: 'medium',
    summary: 'Research interviews are complete and implementation has started.',
    riskSummary: 'No blocking risk is confirmed.',
    decisionSummary: '',
    helpNeeded: '',
    nextAction: 'Confirm the event taxonomy.',
    progressSnapshot: { percent: 42, linkedWorkItemCount: 3 },
    contextSnapshot: {
      health: 'on-track',
      risk: 'medium',
      progress: { percent: 42, linkedWorkItemCount: 3 },
      scope: { teamId: 'core-team' },
      targetDate: '2026-09-21',
      milestones: [],
      dependencies: [],
    },
    changes: [],
    evidence: [],
    authorMemberKey: 'lead@example.com',
    coveredDueAt: '2026-07-08T00:00:00.000Z',
    createdAt: '2026-07-08T09:00:00.000Z',
  },
] satisfies PlanningUpdate[]

/**
 * Planning entity がまだない empty state 用 snapshot です。
 */
export const emptyPlanningSnapshotFixture = {
  schemaVersion: PLANNING_SCHEMA_VERSION,
  revision: 0,
  entities: [],
  dependencies: [],
  workItemDependencies: [],
  workItemLinks: [],
  workItems: [],
  updateTargets: [],
  criticalPath: {
    entityIds: [],
    totalDurationDays: 0,
    slackByEntityId: {},
  },
  workItemDependencySummary: {
    criticalPath: {
      workItems: [],
      totalDurationDays: 0,
      slackByWorkItemKey: {},
    },
    conflicts: [],
    unresolvedBlockerCount: 0,
    affectedProjects: [],
    affectedProjectIds: [],
    affectedMilestoneIds: [],
  },
} satisfies PlanningSnapshot
