import {
  createTranslator,
  type Locale,
} from '../i18n'
import type { PlanningLabels } from './PlanningScreen'

/**
 * PlanningScreen へ渡す locale 済み label を生成します。
 *
 * @param locale - 表示 locale です。
 * @returns Planning UI が必要とする label 一式です。
 */
export function createPlanningLabels(locale: Locale): PlanningLabels {
  const t = createTranslator(locale)
  const statusDateFormatter = new Intl.DateTimeFormat(locale, {
    dateStyle: 'medium',
    timeStyle: 'short',
  })
  return {
    eyebrow: t('planning.eyebrow'),
    title: t('planning.title'),
    description: t('planning.description'),
    viewTabs: t('planning.title'),
    timeline: t('planning.view.timeline'),
    roadmap: t('planning.view.roadmap'),
    portfolio: t('planning.view.portfolio'),
    loading: t('planning.loading'),
    error: t('planning.error'),
    retry: t('planning.action.retry'),
    emptyTitle: t('planning.empty.title'),
    emptyDescription: t('planning.empty.description'),
    timelineTitle: t('planning.view.timeline'),
    timelineDescription: t('planning.description'),
    baseline: t('planning.field.baselineStart'),
    forecast: t('planning.field.forecastEnd'),
    progress: t('planning.field.progress'),
    owner: t('planning.field.owner'),
    health: t('planning.field.health'),
    risk: t('planning.field.risk'),
    status: t('planning.field.status'),
    linkedWorkItems: t('planning.section.workItems'),
    criticalPath: t('planning.section.criticalPath'),
    criticalPathDays: (days) => `${t('planning.section.criticalPath')}: ${days}`,
    slackDays: (days) => `${t('planning.section.criticalPath')}: ${days}`,
    percent: (value) => `${value}%`,
    workItemCount: (count) => `${count} ${t('planning.section.workItems')}`,
    milestoneEditor: t('planning.type.milestone'),
    milestoneDate: t('planning.field.forecastEnd'),
    save: t('planning.action.save'),
    dependencyEditor: t('planning.action.addDependency'),
    predecessor: t('planning.field.predecessor'),
    successor: t('planning.field.successor'),
    dependencyType: t('planning.field.type'),
    dependencyLag: t('planning.field.lagDays'),
    addDependency: t('planning.action.addDependency'),
    cycleRollover: t('planning.action.rollover'),
    sourceCycle: t('planning.section.cycles'),
    targetCycle: t('planning.field.targetCycle'),
    rollover: t('planning.action.rollover'),
    closedCycleRollover: t('planning.rollover.closedSource'),
    noRolloverTarget: t('planning.rollover.noTarget'),
    capacity: (value) => `${t('planning.field.capacity')}: ${value}`,
    roadmapTitle: t('planning.section.hierarchy'),
    roadmapDescription: t('planning.description'),
    goalWorkItems: t('planning.section.workItems'),
    noGoalWorkItems: t('tasks.empty'),
    openWorkItem: t('workspace.action.openTask'),
    entityActions: t('planning.title'),
    archive: t('planning.action.archive'),
    duplicateId: t('planning.field.id'),
    duplicate: t('planning.action.duplicate'),
    moveTarget: t('planning.field.parent'),
    moveToRoot: t('issues.project.unassigned'),
    move: t('planning.action.move'),
    readOnly: t('planning.readOnly'),
    portfolioTitle: t('planning.view.portfolio'),
    portfolioDescription: t('planning.description'),
    entity: t('planning.field.title'),
    entityId: t('planning.field.id'),
    team: t('planning.field.team'),
    project: t('planning.field.project'),
    startDate: t('planning.field.baselineStart'),
    endDate: t('planning.field.baselineEnd'),
    createEntity: t('planning.action.create'),
    create: t('planning.action.create'),
    cadenceWeek: t('planning.cadence.week'),
    cadenceMonth: t('planning.cadence.month'),
    carryOverMove: t('planning.carryOver.move-incomplete'),
    carryOverKeep: t('planning.carryOver.keep-incomplete'),
    statusUpdate: t('planning.section.statusUpdates'),
    statusMessage: t('planning.field.statusMessage'),
    addStatusUpdate: t('planning.action.addStatusUpdate'),
    workItemLinkEditor: t('planning.action.linkWorkItem'),
    workItem: t('planning.section.workItems'),
    cycle: t('planning.type.cycle'),
    milestone: t('planning.type.milestone'),
    goal: t('planning.type.goal'),
    goalFramework: t('planning.field.goalFramework'),
    linkWorkItem: t('planning.action.linkWorkItem'),
    unlinkWorkItem: t('planning.action.unlinkWorkItem'),
    deleteDependency: t('planning.action.delete'),
    reportedHealth: t('planning.field.reportedHealth'),
    rollupHealth: t('planning.field.rollupHealth'),
    noStatusUpdates: t('planning.statusUpdates.empty'),
    statusUpdateMeta: (authorMemberKey, createdAt) =>
      `${authorMemberKey} · ${statusDateFormatter.format(new Date(createdAt))}`,
    entityTypes: {
      cycle: t('planning.type.cycle'),
      milestone: t('planning.type.milestone'),
      release: t('planning.type.release'),
      phase: t('planning.type.phase'),
      goal: t('planning.type.goal'),
      initiative: t('planning.type.initiative'),
      roadmap: t('planning.type.roadmap'),
      portfolio: t('planning.type.portfolio'),
    },
    statuses: {
      proposed: t('planning.status.proposed'),
      planned: t('planning.status.planned'),
      active: t('planning.status.active'),
      paused: t('planning.status.paused'),
      completed: t('planning.status.completed'),
      canceled: t('planning.status.canceled'),
    },
    healthValues: {
      unknown: t('planning.health.unknown'),
      'on-track': t('planning.health.on-track'),
      'at-risk': t('planning.health.at-risk'),
      'off-track': t('planning.health.off-track'),
    },
    riskValues: {
      none: t('planning.risk.none'),
      low: t('planning.risk.low'),
      medium: t('planning.risk.medium'),
      high: t('planning.risk.high'),
      critical: t('planning.risk.critical'),
    },
    dependencyTypes: {
      'finish-to-start': t('planning.dependency.finish-to-start'),
      'start-to-start': t('planning.dependency.start-to-start'),
      'finish-to-finish': t('planning.dependency.finish-to-finish'),
    },
    goalFrameworkValues: {
      goal: t('planning.goalFramework.goal'),
      objective: t('planning.goalFramework.objective'),
      'key-result': t('planning.goalFramework.key-result'),
    },
  }
}
