import {
  WORK_ITEM_CONFIGURATION_SCHEMA_VERSION,
  WORK_ITEM_SCHEMA_VERSION,
} from '@mukuroji/contracts'
import type { CanonicalWorkItem } from './api'
import {
  createDefaultDateRangeTaskSchedule,
  createDefaultDueDateTaskSchedule,
  createDefaultMilestoneTaskSchedule,
  createDefaultUnscheduledTaskSchedule,
} from './model/taskSchedule'

/**
 * TaskPage の Storybook と E2E で共有する Refero タスク fixture です。
 */
export const referoTaskFixtures = [
  {
    schemaVersion: WORK_ITEM_SCHEMA_VERSION,
    revision: 1,
    id: 'wireframe',
    teamId: 'core-team',
    assignedProjectId: 'refero',
    title: '新しいランディングページのワイヤーフレーム作成',
    assigneeUserId: 'sato@example.com',
    creatorMemberKey: 'sato@example.com',
    assigneeEmail: 'sato@example.com',
    assigneeName: '佐藤 花子',
    workflowSchemaVersion: WORK_ITEM_CONFIGURATION_SCHEMA_VERSION,
    workflowStatusId: 'in-progress',
    statusCategory: 'started',
    customFieldValues: {},
    relationIds: [],
    dueDate: '2026-06-03',
    schedule: createDefaultDateRangeTaskSchedule('2026-06-01', '2026-06-03'),
    priority: 'high',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
    source: 'dynamodb',
  },
  {
    schemaVersion: WORK_ITEM_SCHEMA_VERSION,
    revision: 1,
    id: 'brand-guideline',
    teamId: 'core-team',
    assignedProjectId: 'refero',
    title: 'ブランドガイドラインの更新',
    assigneeUserId: 'suzuki@example.com',
    creatorMemberKey: 'suzuki@example.com',
    assigneeEmail: 'suzuki@example.com',
    assigneeName: '鈴木 大輔',
    workflowSchemaVersion: WORK_ITEM_CONFIGURATION_SCHEMA_VERSION,
    workflowStatusId: 'review',
    statusCategory: 'started',
    customFieldValues: {},
    relationIds: [],
    dueDate: '2026-06-05',
    schedule: createDefaultMilestoneTaskSchedule('2026-06-05'),
    priority: 'medium',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
    source: 'dynamodb',
  },
  {
    schemaVersion: WORK_ITEM_SCHEMA_VERSION,
    revision: 1,
    id: 'seo-research',
    teamId: 'core-team',
    assignedProjectId: 'refero',
    title: 'SEO キーワードリサーチ',
    assigneeUserId: 'yamamoto@example.com',
    creatorMemberKey: 'yamamoto@example.com',
    assigneeEmail: 'yamamoto@example.com',
    assigneeName: '山本 健太',
    workflowSchemaVersion: WORK_ITEM_CONFIGURATION_SCHEMA_VERSION,
    workflowStatusId: 'todo',
    statusCategory: 'unstarted',
    customFieldValues: {},
    relationIds: [],
    dueDate: '2026-06-09',
    schedule: createDefaultDueDateTaskSchedule('2026-06-09'),
    priority: 'medium',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
    source: 'dynamodb',
  },
  {
    schemaVersion: WORK_ITEM_SCHEMA_VERSION,
    revision: 1,
    id: 'competitor-report',
    teamId: 'core-team',
    assignedProjectId: 'refero',
    title: '競合サイトの分析レポート作成',
    assigneeUserId: 'tanaka@example.com',
    creatorMemberKey: 'tanaka@example.com',
    assigneeEmail: 'tanaka@example.com',
    assigneeName: '田中 美咲',
    workflowSchemaVersion: WORK_ITEM_CONFIGURATION_SCHEMA_VERSION,
    workflowStatusId: 'done',
    statusCategory: 'completed',
    customFieldValues: {},
    relationIds: [],
    dueDate: '',
    schedule: createDefaultUnscheduledTaskSchedule(),
    priority: 'low',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
    source: 'dynamodb',
  },
] satisfies CanonicalWorkItem[]
