import {
  TRIAGE_CONFIGURATION_SCHEMA_VERSION,
  TRIAGE_ENTRY_SCHEMA_VERSION,
  type TriageConfiguration,
  type TriageEntry,
} from '@mukuroji/contracts'

const fullCapabilities = {
  canAcceptCreate: true,
  canAcceptLink: true,
  canAssign: true,
  canDecline: true,
  canMarkDuplicate: true,
  canReply: true,
  canRequestInformation: true,
  canSnooze: true,
  canViewInternalContext: true,
}

/** Multi-source Team triage fixtures used by Storybook and focused Web tests. */
export const triageEntryFixtures: readonly TriageEntry[] = [
  {
    capabilities: fullCapabilities,
    createdAt: '2026-08-09T00:58:00.000Z',
    events: [
      {
        actorId: 'slack-adapter',
        createdAt: '2026-08-09T00:58:00.000Z',
        id: 'event-chat-created',
        summary: 'Slack thread entered Team triage.',
        type: 'created',
      },
      {
        actorId: 'sla-monitor',
        createdAt: '2026-08-09T01:15:00.000Z',
        id: 'event-chat-sla',
        summary: 'First-response SLA was breached.',
        type: 'sla-breached',
      },
    ],
    id: 'triage-chat-1',
    lastActivityAt: '2026-08-09T01:15:00.000Z',
    permission: {
      canReply: true,
      checkedAt: '2026-08-09T01:16:00.000Z',
      guestVisible: false,
      visibility: 'full',
    },
    receivedAt: '2026-08-09T00:58:00.000Z',
    requester: {
      displayName: 'Aiko Tanaka',
      externalId: 'U-2391',
      guest: true,
    },
    retention: {
      expiresAt: '2026-11-07T00:58:00.000Z',
      policyId: 'retention-90d',
    },
    revision: 3,
    routing: {
      candidates: [
        {
          permitted: true,
          projectId: 'launch-support',
          reason: 'Matched launch and onboarding keywords.',
          ruleId: 'customer-launch',
          score: 0.94,
          teamId: 'core-team',
        },
      ],
      reason: 'Customer launch support rule matched.',
    },
    schemaVersion: TRIAGE_ENTRY_SCHEMA_VERSION,
    sla: {
      breachedAt: '2026-08-09T01:15:00.000Z',
      dueAt: '2026-08-09T01:10:00.000Z',
      escalationDueAt: '2026-08-09T01:40:00.000Z',
      policyId: 'priority-chat',
    },
    source: {
      containerId: 'C-support',
      kind: 'chat',
      messageId: '1723165080.001',
      provider: 'Slack',
      sourceId: 'slack:C-support:1723165080.001',
    },
    sourcePreview: {
      attachmentCount: 2,
      body: 'The launch checklist is blocked because the customer cannot complete workspace provisioning. Logs and a short recording are attached.',
      channelLabel: '#customer-launches',
      commentCount: 8,
      permalink: 'https://example.slack.com/archives/C-support/p1723165080001',
      sanitized: false,
      title: 'Workspace provisioning blocks customer launch',
      truncated: false,
      watcherCount: 4,
    },
    state: 'pending',
    teamId: 'core-team',
    updatedAt: '2026-08-09T01:15:00.000Z',
    workspaceId: 'workspace-demo',
  },
  {
    capabilities: {
      ...fullCapabilities,
      canReply: false,
      canRequestInformation: false,
      canViewInternalContext: false,
    },
    createdAt: '2026-08-09T01:05:00.000Z',
    events: [],
    id: 'triage-email-1',
    lastActivityAt: '2026-08-09T01:18:00.000Z',
    ownerUserId: 'sato@example.com',
    permission: {
      canReply: false,
      checkedAt: '2026-08-09T01:19:00.000Z',
      guestVisible: true,
      reasonCode: 'mailbox-scope-changed',
      visibility: 'metadata-only',
    },
    receivedAt: '2026-08-09T01:05:00.000Z',
    requester: { displayName: 'Billing contact', guest: true },
    retention: { expiresAt: '2026-09-08T01:05:00.000Z' },
    revision: 2,
    routing: { candidates: [], reason: 'Billing mailbox default route.' },
    schemaVersion: TRIAGE_ENTRY_SCHEMA_VERSION,
    sla: {
      dueAt: '2026-08-09T04:00:00.000Z',
      policyId: 'email-standard',
    },
    source: { kind: 'email', provider: 'Email', sourceId: 'mail:2026-08-09:3902' },
    sourcePreview: {
      attachmentCount: 1,
      body: 'This body must not be rendered while metadata-only is active.',
      channelLabel: 'billing@example.com',
      commentCount: 2,
      sanitized: true,
      title: 'Invoice workspace reference',
      truncated: false,
      watcherCount: 1,
    },
    state: 'needs-information',
    teamId: 'core-team',
    updatedAt: '2026-08-09T01:18:00.000Z',
    workspaceId: 'workspace-demo',
  },
  {
    canonicalWorkItem: {
      projectId: 'launch-support',
      teamId: 'core-team',
      workItemId: 'work-item-482',
    },
    capabilities: {
      ...fullCapabilities,
      canAcceptCreate: false,
      canAcceptLink: false,
      canDecline: false,
      canMarkDuplicate: false,
      canRequestInformation: false,
      canSnooze: false,
    },
    createdAt: '2026-08-08T23:40:00.000Z',
    events: [],
    id: 'triage-form-1',
    lastActivityAt: '2026-08-09T00:20:00.000Z',
    ownerUserId: 'owner@example.com',
    permission: {
      canReply: true,
      checkedAt: '2026-08-09T00:20:00.000Z',
      guestVisible: true,
      visibility: 'full',
    },
    projectId: 'launch-support',
    receivedAt: '2026-08-08T23:40:00.000Z',
    requester: { displayName: 'Internal request form', guest: false },
    retention: { expiresAt: '2027-02-05T23:40:00.000Z' },
    revision: 4,
    routing: { candidates: [], reason: 'Published request form route.' },
    schemaVersion: TRIAGE_ENTRY_SCHEMA_VERSION,
    source: {
      formId: 'support-form',
      kind: 'form',
      sourceId: 'submission-490',
      submissionId: 'submission-490',
    },
    sourcePreview: {
      attachmentCount: 0,
      body: 'Create a shared launch follow-up item.',
      channelLabel: 'Launch support form',
      commentCount: 1,
      sanitized: false,
      title: 'Launch follow-up',
      truncated: false,
      watcherCount: 2,
    },
    state: 'accepted',
    teamId: 'core-team',
    updatedAt: '2026-08-09T00:20:00.000Z',
    workspaceId: 'workspace-demo',
  },
  {
    capabilities: {
      canAcceptCreate: false,
      canAcceptLink: false,
      canAssign: false,
      canDecline: false,
      canMarkDuplicate: false,
      canReply: false,
      canRequestInformation: false,
      canSnooze: false,
      canViewInternalContext: false,
    },
    createdAt: '2026-08-09T01:20:00.000Z',
    events: [],
    id: 'triage-webhook-denied',
    lastActivityAt: '2026-08-09T01:20:00.000Z',
    permission: {
      canReply: false,
      checkedAt: '2026-08-09T01:21:00.000Z',
      guestVisible: false,
      reasonCode: 'connector-permission-lost',
      visibility: 'denied',
    },
    receivedAt: '2026-08-09T01:20:00.000Z',
    requester: { displayName: 'Restricted actor', guest: false },
    retention: {
      expiresAt: '2026-08-10T01:20:00.000Z',
      redactedAt: '2026-08-09T01:21:00.000Z',
    },
    revision: 1,
    routing: { candidates: [], reason: 'Restricted routing context.' },
    schemaVersion: TRIAGE_ENTRY_SCHEMA_VERSION,
    source: { connectorId: 'connector-private', kind: 'webhook', sourceId: 'restricted-event' },
    sourcePreview: {
      attachmentCount: 0,
      body: 'This denied body must never render.',
      commentCount: 0,
      sanitized: true,
      title: 'This denied title must never render',
      truncated: false,
      watcherCount: 0,
    },
    state: 'pending',
    teamId: 'core-team',
    updatedAt: '2026-08-09T01:21:00.000Z',
    workspaceId: 'workspace-demo',
  },
]

/** Versioned Team triage configuration fixture used by settings stories. */
export const triageConfigurationFixture: TriageConfiguration = {
  allowedBulkActions: ['assign', 'decline', 'snooze'],
  retentionDays: 90,
  revision: 6,
  rotations: [
    {
      id: 'support-rotation',
      memberUserIds: ['owner@example.com', 'sato@example.com'],
      name: 'Support rotation',
      nextIndex: 1,
    },
  ],
  rules: [
    {
      enabled: true,
      id: 'customer-launch',
      keywords: ['launch', 'provisioning'],
      name: 'Customer launches',
      order: 0,
      owner: { rotationId: 'support-rotation', type: 'rotation' },
      projectId: 'launch-support',
      sourceKinds: ['chat', 'form'],
      teamId: 'core-team',
    },
  ],
  schemaVersion: TRIAGE_CONFIGURATION_SCHEMA_VERSION,
  slaPolicies: [
    {
      escalationMinutes: 30,
      escalationOwnerUserId: 'owner@example.com',
      id: 'priority-chat',
      name: 'Priority chat',
      responseMinutes: 15,
      sourceKinds: ['chat'],
    },
  ],
  teamId: 'core-team',
  updatedAt: '2026-08-09T00:30:00.000Z',
  workspaceId: 'workspace-demo',
}
