/** Analytics module public application and domain surface. */
export {
  DynamoDbDashboardSummaryClient,
  type DashboardSummaryAccessContext,
  type DashboardSummaryClient,
  type DashboardSummaryResponse,
} from './adapter-out/dynamodb/dashboard-summary-client'
export {
  createAnalyticsScheduleRenderer,
  processAnalyticsSchedule,
  renderInAppAnalyticsArtifact,
  resolveAnalyticsScheduleProcessingTime,
  type AnalyticsScheduleEvent,
} from './adapter-in/schedules/analytics-schedule'
export {
  AnalyticsError,
  calculateAnalyticsNextRunAt,
  compareDynamoDbStringSortKeys,
  createAnalyticsCsv,
  createAnalyticsDeliveryRecordKey,
  createAnalyticsEvidenceCursor,
  createAnalyticsNextDeliveryAtRecordKey,
  createAnalyticsPdf,
  createAnalyticsPermissionScopeHash,
  createAnalyticsScheduleShard,
  createAnalyticsSnapshot,
  createAnalyticsSnapshotListCursor,
  normalizeAnalyticsEvidenceInput,
  normalizeAnalyticsExportLocale,
  normalizeAnalyticsQueryInput,
  parseAnalyticsEvidenceCursor,
  queryAnalyticsEvidence,
  validateAnalyticsSnapshotRecordSize,
  DynamoDbAnalyticsRepository,
  type AnalyticsDeliveryReceipt,
  type AnalyticsDeliveryReceiptResult,
  type AnalyticsDueReportPage,
  type AnalyticsDueReportReference,
  type AnalyticsEngineInput,
  type AnalyticsEvidenceEngineInput,
  type AnalyticsReportPage,
  type AnalyticsRepository,
  type AnalyticsSnapshotPage,
} from './analytics'
