import type {
  EnterpriseProvisioningImpact,
  EnterpriseScimTokenResponse,
  EnterpriseSecuritySnapshot,
  EnterpriseServiceAccountCredentialResponse,
} from './api'

/**
 * Storybook と UI test で使用する enterprise security 標準 snapshot です。
 */
export const enterpriseSecuritySnapshotFixture = {
  assignablePermissionIds: [
    'workspace.manage',
    'members.manage',
    'work-items.write',
    'security.manage',
    'automation.manage',
  ],
  assignableRoleIds: {
    groupMappings: {
      project: [
        'project:manager',
        'project:member',
        'project:viewer',
        'custom:security-reviewer',
      ],
      team: [
        'team:manager',
        'team:member',
        'custom:security-reviewer',
      ],
      workspace: [
        'workspace:admin',
        'workspace:member',
        'workspace:guest',
        'custom:security-reviewer',
      ],
    },
    serviceAccounts: [
      'workspace:member',
      'custom:security-reviewer',
    ],
  },
  breakGlassAdministrators: [
    {
      email: 'emergency-admin@example.com',
      id: 'break-glass-primary',
      lastTestedAt: '2026-07-15T02:00:00.000Z',
      mfaConfigured: true,
      status: 'active',
      version: 3,
    },
  ],
  capabilities: {
    canManageAccess: true,
    canManageIdentity: true,
    canManageMappings: true,
    canManagePrivilegedAccess: true,
    canManageProvisioning: true,
    canManageRoles: true,
    canManageSessions: true,
    canView: true,
    canViewAccess: true,
    canViewIdentity: true,
    canViewPrivileged: true,
    canViewProvisioning: true,
    canViewSessions: true,
  },
  domains: [
    {
      domain: 'example.com',
      id: 'domain-example-com',
      status: 'verified',
      verificationRecordName: '_mukuroji-verification.example.com',
      verifiedAt: '2026-07-14T06:00:00.000Z',
      version: 2,
    },
    {
      domain: 'subsidiary.example',
      id: 'domain-subsidiary-example',
      status: 'pending',
      verificationRecordName: '_mukuroji-verification.subsidiary.example',
      version: 1,
    },
  ],
  identityProvider: {
    clientId: 'mukuroji-production',
    displayName: 'Example Okta',
    enforced: false,
    id: 'provider-okta',
    issuer: 'https://example.okta.com/app/mukuroji',
    lastTestSucceeded: true,
    lastTestedAt: '2026-07-16T05:30:00.000Z',
    metadataUrl: 'https://example.okta.com/app/mukuroji/sso/saml/metadata',
    protocol: 'saml',
    ssoUrl: 'https://example.okta.com/app/mukuroji/sso/saml',
    status: 'verified',
    version: 5,
  },
  mappings: [
    {
      directoryGroupId: '00g-engineering',
      directoryGroupName: 'Engineering',
      id: 'mapping-engineering',
      identityProviderId: 'provider-okta',
      roleId: 'workspace:member',
      scopeId: 'workspace-demo',
      scopeName: 'Workspace',
      scopeType: 'workspace',
      version: 2,
    },
    {
      directoryGroupId: '00g-security',
      directoryGroupName: 'Security operations',
      id: 'mapping-security',
      identityProviderId: 'provider-okta',
      roleId: 'custom:security-reviewer',
      scopeId: 'core-team',
      scopeName: 'Core team',
      scopeType: 'team',
      version: 1,
    },
  ],
  permissions: [
    {
      description: 'Workspace settings and directory structure can be changed.',
      group: 'workspace',
      id: 'workspace.manage',
      name: 'Configure workspace',
      privileged: true,
    },
    {
      description: 'Members, invitations, and role assignments can be managed.',
      group: 'members',
      id: 'members.manage',
      name: 'Manage members',
      privileged: true,
    },
    {
      description: 'Work items, comments, and files can be edited.',
      group: 'content',
      id: 'work-items.write',
      name: 'Write content',
      privileged: false,
    },
    {
      description: 'Identity provider and session policy can be changed.',
      group: 'security',
      id: 'security.manage',
      name: 'Manage security',
      privileged: true,
    },
    {
      description: 'Automation rules and execution retries can be changed.',
      group: 'automation',
      id: 'automation.manage',
      name: 'Manage automation',
      privileged: true,
    },
  ],
  provisioningLogs: [
    {
      attempts: 1,
      completedAt: '2026-07-17T01:02:00.000Z',
      correlationId: 'correlation-sync-17',
      createdAt: '2026-07-17T01:00:00.000Z',
      id: 'provisioning-log-success',
      operation: 'scim',
      retryable: false,
      status: 'succeeded',
      summary: '12 users and 4 groups reconciled without conflicts.',
    },
    {
      attempts: 2,
      completedAt: '2026-07-16T03:04:00.000Z',
      correlationId: 'correlation-sync-16',
      createdAt: '2026-07-16T03:00:00.000Z',
      id: 'provisioning-log-failed',
      operation: 'reconcile',
      retryable: true,
      status: 'failed',
      summary: 'One group mapping referenced a role that no longer exists.',
    },
  ],
  roles: [
    {
      assignmentCount: 2,
      description: 'Full Workspace administration.',
      guestAssignable: false,
      id: 'workspace:owner',
      kind: 'built-in',
      name: 'Owner',
      permissionIds: [
        'workspace.manage',
        'members.manage',
        'work-items.write',
        'security.manage',
        'automation.manage',
      ],
      version: 1,
    },
    {
      assignmentCount: 14,
      description: 'Standard Workspace collaboration.',
      guestAssignable: false,
      id: 'workspace:member',
      kind: 'built-in',
      name: 'Member',
      permissionIds: ['work-items.write'],
      version: 1,
    },
    {
      assignmentCount: 4,
      description: 'Workspace administration without owner-only actions.',
      guestAssignable: false,
      id: 'workspace:admin',
      kind: 'built-in',
      name: 'Workspace administrator',
      permissionIds: [
        'workspace.manage',
        'members.manage',
        'work-items.write',
        'security.manage',
        'automation.manage',
      ],
      version: 1,
    },
    {
      assignmentCount: 2,
      description: 'Read-only external collaboration.',
      guestAssignable: true,
      id: 'workspace:guest',
      kind: 'built-in',
      name: 'Guest',
      permissionIds: [],
      version: 1,
    },
    {
      assignmentCount: 5,
      description: 'Manages a team and its content.',
      guestAssignable: false,
      id: 'team:manager',
      kind: 'built-in',
      name: 'Team manager',
      permissionIds: ['work-items.write', 'members.manage'],
      version: 1,
    },
    {
      assignmentCount: 9,
      description: 'Collaborates within a team.',
      guestAssignable: false,
      id: 'team:member',
      kind: 'built-in',
      name: 'Team member',
      permissionIds: ['work-items.write'],
      version: 1,
    },
    {
      assignmentCount: 3,
      description: 'Manages a project and its content.',
      guestAssignable: false,
      id: 'project:manager',
      kind: 'built-in',
      name: 'Project manager',
      permissionIds: ['work-items.write', 'automation.manage'],
      version: 1,
    },
    {
      assignmentCount: 8,
      description: 'Collaborates within a project.',
      guestAssignable: false,
      id: 'project:member',
      kind: 'built-in',
      name: 'Project member',
      permissionIds: ['work-items.write'],
      version: 1,
    },
    {
      assignmentCount: 6,
      description: 'Views a project without editing.',
      guestAssignable: true,
      id: 'project:viewer',
      kind: 'built-in',
      name: 'Project viewer',
      permissionIds: [],
      version: 1,
    },
    {
      assignmentCount: 3,
      description: 'Reviews security settings without editing them.',
      guestAssignable: false,
      id: 'custom:security-reviewer',
      kind: 'custom',
      name: 'Security reviewer',
      permissionIds: ['security.manage'],
      version: 4,
    },
  ],
  scim: {
    endpointUrl: 'https://api.example.test/scim/v2',
    identityProviderId: 'provider-okta',
    lastSyncAt: '2026-07-17T01:02:00.000Z',
    status: 'ready',
    tokenGeneration: 3,
    tokenLastFour: 'A7xQ',
    version: 3,
  },
  serviceAccounts: [
    {
      allowedSourceCidrs: ['203.0.113.0/24'],
      createdAt: '2026-07-10T03:00:00.000Z',
      credentialExpiresAt: '2026-10-08T03:00:00.000Z',
      credentialGeneration: 2,
      credentialLifetimeDays: 90,
      id: 'service-release-bot',
      lastUsedAt: '2026-07-17T00:10:00.000Z',
      name: 'Release bot',
      roleId: 'workspace:member',
      scopeType: 'workspace',
      status: 'active',
      version: 2,
    },
  ],
  sessionPolicy: {
    allowedGuestDomains: ['partner.example'],
    externalCollaboratorsAllowed: true,
    guestSessionLifetimeMinutes: 240,
    guestsAllowed: true,
    idleTimeoutMinutes: 30,
    ipAllowlist: ['203.0.113.0/24', '2001:db8:1234::/48'],
    mfaRequired: true,
    reauthenticationMinutes: 120,
    sensitiveActionReauthenticationMinutes: 15,
    sessionLifetimeMinutes: 480,
    version: 6,
  },
  ssoPrerequisites: {
    breakGlassReady: true,
    domainReady: true,
    providerReady: true,
  },
} satisfies EnterpriseSecuritySnapshot

/**
 * Reconciliation dry-run の差分あり preview fixture です。
 */
export const enterpriseProvisioningImpactFixture: EnterpriseProvisioningImpact = {
  blocking: false,
  counts: {
    groupsCreated: 1,
    groupsUpdated: 2,
    sessionsRevoked: 4,
    usersCreated: 3,
    usersDeactivated: 2,
    usersUpdated: 8,
  },
  expiresAt: '2026-07-18T04:15:00.000Z',
  hasChanges: true,
  previewId: 'preview-enterprise-reconcile-1',
  warnings: [
    'Two users will lose access immediately and their active sessions will be revoked.',
    'One unmapped directory group will remain without a Workspace role.',
  ],
}

/**
 * SCIM token rotate API の一回限り secret fixture です。
 */
export const enterpriseScimTokenResponseFixture = {
  scim: {
    ...enterpriseSecuritySnapshotFixture.scim,
    tokenGeneration: 4,
    tokenLastFour: 'N3wT',
    version: 4,
  },
  token: 'scim_storybook_one_time_token',
} satisfies EnterpriseScimTokenResponse

/**
 * Service account create/rotate API の一回限り credential fixture です。
 */
export const enterpriseServiceAccountCredentialResponseFixture = {
  serviceAccount: {
    allowedSourceCidrs: [],
    createdAt: '2026-07-18T04:00:00.000Z',
    credentialExpiresAt: '2026-10-16T04:00:00.000Z',
    credentialGeneration: 1,
    credentialLifetimeDays: 90,
    id: 'service-data-export',
    name: 'Data export',
    roleId: 'custom:security-reviewer',
    scopeType: 'workspace',
    status: 'active',
    version: 1,
  },
  token: 'svc_storybook_one_time_token',
} satisfies EnterpriseServiceAccountCredentialResponse
