/** Automation module public application and domain surface. */
export {
  AutomationEngine,
  AutomationError,
  createAutomationActionId,
  createAutomationExecutionId,
  createAutomationScheduleShard,
  createBulkOperationToken,
  createRecurringExecutionId,
  evaluateAutomationCondition,
  getNextRecurringOccurrence,
  getRecurringOccurrences,
  isAutomationValue,
  matchesAutomationTrigger,
  normalizeAutomationActionFailure,
  selectCatchUpOccurrences,
  toAutomationInboundWebhookEndpoint,
  validateApplyAutomationTemplateInput,
  validateAutomationInboundWebhookLifecycleInput,
  validateCreateAutomationInboundWebhookEndpointInput,
  validateCreateAutomationRuleInput,
  validateCreateAutomationTemplateInput,
  validateCreateRecurringWorkInput,
  validateRecurringSchedule,
  validateUpdateAutomationInboundWebhookEndpointInput,
  type AutomationActionExecutionContext,
  type AutomationActionExecutor,
  type AutomationClient,
  type AutomationConditionContext,
  type AutomationEvent,
  type AutomationEventChange,
  type AutomationExecutionClaimToken,
  type AutomationExecutionDefinitionGuard,
  type AutomationExecutionPage,
  type AutomationExecutionQuery,
  type AutomationExecutionReservation,
  type AutomationInboundWebhookDeliveryInput,
  type AutomationInboundWebhookDeliveryResult,
  type AutomationInboundWebhookEndpointRecord,
  type AutomationInboundWebhookProvisioning,
  type AutomationInboundWebhookProvisioningOperation,
  type AutomationInboundWebhookSecretCleanup,
  type BulkItemApplyResult,
  type BulkItemPreviewResult,
  type BulkOperationAdapter,
} from './automation'
export type {
  AutomationInboundWebhookSecretReference,
  AutomationInboundWebhookSecretStore,
} from './automation-inbound-webhook'
