/** Notifications module public application and domain surface. */
export {
  NOTIFICATION_PREFERENCES_KEY,
  NotificationError,
  createNotificationDeliveryPlan,
  createNotificationRecipientKey,
  parseStoredNotificationPreferences,
  type CountUnreadNotificationsInput,
  type ListNotificationsInput,
  type MarkAllNotificationsReadInput,
  type NotificationAction,
  type NotificationChannels,
  type NotificationClient,
  type NotificationDeliveryPlan,
  type NotificationFilter,
  type NotificationFrequency,
  type NotificationItem,
  type NotificationPage,
  type NotificationPreferences,
  type NotificationQuietHours,
  type NotificationRecipientInput,
  type NotificationState,
  type NotificationVisibilityFilter,
  type SaveNotificationPreferencesInput,
  type UpdateNotificationInput,
  type UpdateNotificationPreferencesInput,
} from './notifications'
export {
  createNotificationScheduleHandler,
  parsePlanningUpdateTargetScheduleProjection,
  type PlanningScheduledNotificationKind,
  type PlanningUpdateNotificationCadence,
  type PlanningUpdateTargetReference,
  type PlanningUpdateTargetScheduleProjection,
} from './adapter-in/schedules/notification-schedule'
